language: node_js

node_js:
  - lts/*

env:
  global:
    - secure: ZTTkIEjfAmfosbYYQcNQU+u9s2K7FAk7wcgDo/Z7cB8c+er1IGNhmc82QfJep9CBmNqX8UWFwW2RCWl1c8SnFJQ3VjrBPFhocakRW34bAmlDRtFYQJy1F3TbIIYMkdehM0Gj2oSaXK8JhComZvVa8BkENvriqmrbGDEKl5xbc65g/FS1SIq7EqRgr68yKwNVzEJRBL3Cn50zdtvxajRGzVwkiWZ+yg/S7z6yR6csQqfsTctrhcM8+LrmSunZRrfCdDsWivNjK7js91a/Pg4X/yvkmeom5eIe7sKqFtYC8oUgfPf28fgOKsgcVI7NWJ7wl0vYvA+6YLQXXsrQse11h9Ua7xNlErNrWk7lGuni1Dak/VAdtnn/JlHJQ5+bCSF4I3uhip+xTQu3o/cde5BcTCGP7T5+EOTre0IoT6iI+ShoslUsx71VnKeWJt/0ESPuIWs0rFNm+ZZdGLHNzsWyR/VsYZT0gjM9DcAU3Yf58SyJn44fQSyCiSqu+yQJcBQ+RdG4tB16yd107o8zN25oizV9az+Q05X+C9XXK9xKpKwLhdPbNpGkHh3PSuFWSgvAsiY56RZ/nwJxzbbPPVcCp8PhVABj1kaYvBOmCmKaaxg5yNxdsimNHaPwktVGXMImUHRwW4a3AG1yYSoDs+H2AOQUpvoOOnLeLORQlJF2p+E=
    - secure: Y+eCt1m4xHRdGDJ94s24hGt77qB3nzgoLOPj6FUcaOh3NgH8A/Gs6rQgUkC847GK0lsoH8QJYjAAHEtPaN8kdVdbvzF0kOIb1CSWOGOHIFnAbgY3lyaKn6dAho/dNOmv+W+5+YOPWzVlW+QeR/DShGWz1G/NT2fB+eGCv5sASli3EJ1Z7rsZ1l/PYWMzgFpOVK+8FQ9Z/THqWVRn4Y+nIW9fCWhvOmeJ858PBEp7ufs9xEe1HNkOoHscXwX4B4zg6O45SS64yxGUr6rPAdVUgLw8QSoniXlPGHFsk+VE3P48X32DWVcnzUVujPXtTzLMkgw2eDKcWc0ZgF/7Wdm96MqBSt1evVMO+sP59EuNWKiaxL76V/AaeOOwZp8+ON+2fZlshmL1RXGH8dJV1o/O+YIj4ak9nkgVcJiryf09LP7QqX/KVVzrflIQdL46EiZ3+WeSDQkF+NZ2rgs1sN4c/qo/qc1eaUXLtOeZjB0heIgSKx/UiOfVzOkrbtjdvy+PrkYnrTqDZnzvbKX2Gjjxq7J3BkV5XYOEEQErE2xuXddDYUbuUQZIIsGVODWV5ZR0cTzEmyFCYe1m/tvl8nYCq5VwV3/LMT63Nw1/iqqH7VHIaFm7L1iQUnJcke5un15gpYrEqGvPWoWhf5ef5TpVnP2KtW4Gm1f5nR+JStxw6uk=

jobs:
  include:
    - stage: test
      services:
        - mysql
      env:
        - NODE_ENV=test
        - secure: FmxJ47KaOTY2fNJOnIohMMlJM8Q7gjfi4u/gz/9k1miGYrzds0N7vUjH+N6jjIxPgH9geibEURfUGgv4YiqEXNV+k4S9QPBK1DiuSq92fuDFx6bBCuwNhs+OJc4zdyuNE4iiXfSTymLF8ZK4ubyz3U9PDMdqU3OVP2OOWF+/QuBMv08O0g2hF/BewQtP8iTlo+X4SuTjqg8tl9K3IgEBXTee2+v419LuhDVTpSPpzGA2koaeMLYpdkMzgofAFVu2R6zqY3UvCbKHawbaJrl/POioAwxKnaUblBFDX5jup8U0YtXxCiy+3Ecn9sb0IJY+2vpg0D4l7dzizWpLmAGBTp7G9JfKNR2NgEqfpcEih6MaAF/MW6NriZsskAIxTPjYq3Iy0rD1COYEkq1NIJYvNoKU/ptuwhnP+YYgUIz6hztE/HxiSqdPzY0+GHfqGLb2MsrTysiLRMk3ohyFlhOebfiS4PzFC+8jYisVOtsEMcaGQDkHwK/315Eerz8N1OqOSf9H1nzg8gWaPDacblg3+REZ+PJpeR6G1KVHOjIc23Anbio6+sJETNgZqMGOtYWjDneFYchnJZeyn8Y0gj1YkEd/MPUSLW11Ipg2jqAvg74WwaDUYP5uN4Cq+i/eJtUshQMnC7PWi6T30ASM4eVYf+2yr4by2xrMHl7Xl4RP310=
      before_install:
        - npm i npm yarn -g
        - mysql -e 'CREATE DATABASE database_test;'
      script:
        - yarn lint
        - yarn start:test
        - yarn test
    - stage: deploy
      env:
        - NODE_ENV=production
      before_install:
        - openssl aes-256-cbc -K $encrypted_f9850b56028b_key -iv $encrypted_f9850b56028b_iv -in travis-ci_rsa.enc -out travis-ci_rsa -d
        - chmod 600 travis-ci_rsa
        - mv travis-ci_rsa ~/.ssh/id_rsa
        - mv travis-ci_rsa.pub ~/.ssh/id_rsa.pub
      script:
        - rm -rf node_modules yarn.lock
        - yarn install --production=false
        - yarn build:pro
        - docker login repo.treescale.com --username=nulpas --password=$TREESCALE_PS
        - docker build -t repo.treescale.com/nulpas/sds-circe-api:latest . --build-arg nodeEnv=$NODE_ENV --build-arg jwtSecret=$JWT_SECRET --build-arg saltRounds=$SALT_ROUNDS
        - docker push repo.treescale.com/nulpas/sds-circe-api:latest
      after_success:
        - JWT_SECRET=$JWT_SECRET SALT_ROUNDS=$SALT_ROUNDS NODE_ENV=$NODE_ENV TREESCALE_PS=$TREESCALE_PS bash ./scripts/deploy.sh

stages:
  - name: test
    if: "(type = push AND branch != master) OR (type = pull_request AND branch = master)"
  - name: deploy
    if: type = push AND branch = master
