language: node_js

node_js:
  - lts/*

env:
  global:
    - secure: FP7Fgn9qrO2WHSifNoeykhvCKJrDGcXY+IwkqCG3KbcrzirYXsS9IgqOkaxll1EJNCVpuDm4QQO1cbF0qjhW3AcA9oOmZQQZ5zT2f2Wk02L9YRwSVmPf4wwUfdzBMNLqDeAmybyBIjqjhVI+e2VdmH9rOK8gQsHm2OxBfLEVfKn++sur5TGs9yMuXY8aqggyjlIgKYBXQL2duTsYKiSlnbHJrVHYgVn9PKeUomcLHZuP7jWRtJgRjm+7FS19qmvu7Z53u3FyRrQRpU3TIy8bQrzmkllNILxlhKvQF7UbXH0pUfFauQRdmHQhIUEvSbR0adLcDacwfZLq3wbfjtU6OXCkEhpQygKgxkC5dt1EZeaIw6bJG2ym4XsfmfCTDts7tLVstIewVRmu5W9bb4OANjrfQHCG2Qx5B92tTAwxUO6e3IkEDuvmbMfpeBeYNaEcdEwwKGFk3IhupMq5c+qHhcHsx1F5NQazHvHIOdrUdwQq+3zw6r+TuLavCkc7t4jCn7NezuJux/9qjONLcFVYfh77dcfyrtDt4dN7CTp/sq+WrW9f2UbNjkz5g1fY9aLpGGmxIhzjwPZ8NxXaSFymmA2qv4mLHQGaNsBh10E4bBuLDkp3mKDmMsoKIj7tLnQQeE0HtHp6M7kTo4UAM6Nwb5NYsOonzxoFN54GbebYq4M=
    - secure: UwHAHzakoPOo9qZHmKHL5ZdCErW7ypAkz4KHZ1NWl3l001Szbh+24d9OILvo93bJkW0yGMP4xIOfe0dYlLTbIEtJCdITjS1LtbYuYRRqjyQwVRYUaKmzHhwlOLn41dRuTk/hsdZzvgyB3ROt50YVcmnedf3fspshcw7fkSumCi1P6pI4/7RcGKJ1UFwokAhnJAnVJ2pQFtIjeJVZ2KeNkJSIkQf4yEqy2JEbt3TFOfnIuAQgYlBAeqRQe79bUZTWJhbZK0C1/tH7WD7o6BB55nbgzwNEetU0dCoLFwMH2l5auvk96jaTHHsUAhoMd7KxJT/2nBRkQ5kWSCgDnsPt7Rl36HKNkYvl6AR0T8rPN2SNAsUDjESnDvuyepjQhUQu3N3EXoZUVs21LUkTad3UkWQW9/1QW/964QsDripl5oyngw25YFppXKH0GK3KytR+1wwoSF0Gpp//2kLFO6gNBZEe6D8nuvDbrNJ7nYt+rkHpwFOnYvyWkhhEUz0IrCUUow7OUCK6j0IjM/n1ammcutA1pI7g5xCp2m99crdLZGfUPIDdFWpfSCAgITad2YW2R7o0IXlgqovCQ2x3mBs3B3KttZUZefXXSj/DpVGvqRJb1+79toFb+6ifWgntIPFqpVfCuyw5b3B41jqPK7KoQDX1b3Spuc00tDdVthkYDuc=

jobs:
  include:
    - stage: test
      services:
        - mysql
      env:
        - NODE_ENV=test
      before_install:
        - npm i npm yarn -g
        - mysql -e 'CREATE DATABASE database_test;'
      script:
        - yarn lint
        - yarn start:test
        - yarn test
    - stage: deploy
      env:
        - NODE_ENV=production
      before_install:
        - openssl aes-256-cbc -K $encrypted_6dd494723194_key -iv $encrypted_6dd494723194_iv -in travis-ci_rsa.enc -out travis-ci_rsa -d
        - chmod 600 travis-ci_rsa
        - mv travis-ci_rsa ~/.ssh/id_rsa
        - mv travis-ci_rsa.pub ~/.ssh/id_rsa.pub
      after_success:
        - JWT_SECRET=$JWT_SECRET SALT_ROUNDS=$SALT_ROUNDS NODE_ENV=$NODE_ENV bash ./scripts/deploy.sh

stages:
  - name: test
    if: "(type = push AND branch != master) OR (type = pull_request AND branch = master)"
  - name: deploy
    if: type = push AND branch = master
